<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Slim' => array($vendorDir . '/slim/slim'),
    'PHPQRCode' => array($vendorDir . '/aferrandini/phpqrcode/lib'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
);
